### ISSUE TITLE
Bootstrap brainstorm

### ISSUE THREAD

**Issue by moreati** [moreati/ansible-uv#1]
Continuation of https://social.moreati.org.uk/@jamescooke@fosstodon.org/113560076471527990. `d12.mynet` is a convenient LXC container running Debian 12. I've uninstalled all system wide Pythons.

```yaml
- name: Bootstrap UV and Python
  hosts: d12.mynet
  gather_facts: false
  vars:
    uv_installer_path: uv_install.sh
    uv_installer_url: https://astral.sh/uv/install.sh
    uv_path: ~/.local/bin/uv
    
    uv_python_path: 
    uv_python_version: "3.12"
  tasks:
    #- set_fact:
    #    uv_installer_content: "{{ lookup('url', uv_installer_url) }}"

    - name: Install uv
      # curl --location --silent --show-error --fail '{{ uv_installer_url }}' | sh
      #raw: "{{ lookup('url', uv_installer_url) }}"
      raw: "{{ lookup('file', uv_installer_path) }}"

    - name: Install uv python
      raw: uv python install --color never --no-progress "{{ uv_python_version }}"


- name: Bootstrap virtualenv
  hosts: d12.mynet
  gather_facts: true
  vars:
    # TODO less hard coding
    ansible_python_interpreter: .local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/bin/python3.12
  tasks:
    - name: Create virtualenv
      moreati.uv.pip:
        name:
          - requests
        virtualenv: "{{ ansible_facts.user_dir }}/.ansible_venv"
```

Result
```
➜  uv git:(main) ✗ ansible-playbook -i ~/ansible_inventory.yml bootstrap.yml

PLAY [Bootstrap UV and Python] ***************************************************************************

TASK [Install uv] ****************************************************************************************
changed: [d12.mynet]

TASK [Install uv python] *********************************************************************************
changed: [d12.mynet]

PLAY [Bootstrap virtualenv] ******************************************************************************

TASK [Gathering Facts] ***********************************************************************************
ok: [d12.mynet]

TASK [Create virtualenv] *********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'packaging'
fatal: [d12.mynet]: FAILED! => changed=false 
  msg: Failed to import the required Python library (packaging) on d12's Python /root/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/bin/python3.12. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter

PLAY RECAP ***********************************************************************************************
d12.mynet                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by moreati** [comment]
I had to download https://astral.sh/uv/install.sh -> `uv_install.sh` on the controller (unexpected forking error trying to use `url` lookup plugin on macOS). Final failure looks like a bug in `moreti.uv.pip`.

Possible features for moreati.uv
- bootstrap task(s) in role(s)
- facts module or info module to determine uv installed pythons. Can a facts module be shell script?
- moreati.uv.python module
- cached facts for uv installed pythons
- allow control of alternative sources for uv_install.sh or uv to download from
- Does `uv` output json? Does `jc` have a parser for it?

**Comment by jamescooke** [comment]
Thanks for creating this and sharing code 👍🏻 

I've got a bunch of code (3 roles and a playbook) which I'm using for Step 1, 2 and 3 as we discussed on Masto... They're outlined below.

Meanwhile, here's the error I'm getting at step 3 when trying to use the venv built at `~/ansible_venv`:

## Step 1: install UV

This is performed by a role called "python" and it has a `tasks/main` of:

```yaml
---

- name: Upgrade uv, install it if it's not in place

  block:

    - name: Upgrade uv
      become: true
      ansible.builtin.command:
        cmd: uv self update
      register: python_uv_update_result
      changed_when: python_uv_update_result.rc == 0

  rescue:

    - name: Make a temp dir
      ansible.builtin.tempfile:
        state: directory
      register: python_uv_dl_dir

    - name: Download install script
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        # uv's web server calls the file "uv-installer.sh" which is confusing,
        # so pin the name in dest here:
        dest: "{{ python_uv_dl_dir.path }}/install.sh"

    - name: Do install
      become: true
      ansible.builtin.command:
        cmd: "sh {{ python_uv_dl_dir.path }}/install.sh"
        creates: /usr/local/bin/uv
      environment:
        UV_INSTALL_DIR: /usr/local/bin/
        INSTALLER_NO_MODIFY_PATH: 1

    - name: Upgrade uv
      become: true
      ansible.builtin.command:
        cmd: uv self update
      register: python_uv_update_result2
      changed_when: python_uv_update_result2.rc == 0

- name: Install Pythons
  ansible.builtin.command:
    cmd: uv python install 3.13
  register: python_uv_install_pythons_result
  changed_when: python_uv_install_pythons_result.rc == 0
```

The result is an install of `uv` as:

```console
slinger@slinger:~ $ command -v uv
/usr/local/bin/uv
slinger@slinger:~ $ ls -l $(command -v uv)
-rwxr-xr-x 1 1001 127 29013008 Nov 27 17:51 /usr/local/bin/uv
```

## Step 2: Build venv

Next the role "ansible_venv" kicks in and builds the virtual environment:

```yaml
---

- name: Make ansible_venv
  ansible.builtin.command:
    cmd: "uv venv --no-project --python 3.13 {{ ansible_facts.user_dir }}/.ansible_venv"
  register: ansible_venv_create_result
  changed_when: ansible_venv_create_result.rc == 0
```

Probably not the best idempotency provision or use of vars, but there it is.

This gives and installed Python binary runnable by everyone including root.

```console
slinger@slinger:~ $ ls -l .ansible_venv/
total 16
drwxr-xr-x 2 slinger slinger 4096 Nov 29 12:38 bin
-rw-r--r-- 1 slinger slinger   43 Nov 29 12:38 CACHEDIR.TAG
drwxr-xr-x 3 slinger slinger 4096 Nov 29 12:38 lib
lrwxrwxrwx 1 slinger slinger    3 Nov 29 12:38 lib64 -> lib
-rw-r--r-- 1 slinger slinger  176 Nov 29 12:38 pyvenv.cfg
slinger@slinger:~ $ ls -l .ansible_venv/bin
total 44
-rw-r--r-- 1 slinger slinger 3703 Nov 29 12:38 activate
-rw-r--r-- 1 slinger slinger 2259 Nov 29 12:38 activate.bat
-rw-r--r-- 1 slinger slinger 2610 Nov 29 12:38 activate.csh
-rw-r--r-- 1 slinger slinger 4174 Nov 29 12:38 activate.fish
-rw-r--r-- 1 slinger slinger 3859 Nov 29 12:38 activate.nu
-rw-r--r-- 1 slinger slinger 2762 Nov 29 12:38 activate.ps1
-rw-r--r-- 1 slinger slinger 2383 Nov 29 12:38 activate_this.py
-rw-r--r-- 1 slinger slinger 1728 Nov 29 12:38 deactivate.bat
-rw-r--r-- 1 slinger slinger 1215 Nov 29 12:38 pydoc.bat
lrwxrwxrwx 1 slinger slinger   84 Nov 29 12:38 python -> /home/slinger/.local/share/uv/python/cpython-3.13.0-linux-aarch64-gnu/bin/python3.13
lrwxrwxrwx 1 slinger slinger    6 Nov 29 12:38 python3 -> python
lrwxrwxrwx 1 slinger slinger    6 Nov 29 12:38 python3.13 -> python
slinger@slinger:~ $ sudo .ansible_venv/bin/python --version
Python 3.13.0
```

## Step 3: Trying to use this Python

This is where the problems come with what I thought was "switching the Python interpreter from "discovered" for steps 1 and 2 to declared for steps 3." - but actually it looks like something about the Python installed with uv means it can't be used in the way that `sh` is called on it by Ansible...

So with a very simple playbook to reproduce:

```yaml
---

- name: Set up slinger
  hosts: slinger
  remote_user: slinger

  vars:
    ansible_python_interpreter: "/home/slinger/.ansible_venv/bin/python"

  tasks:
    - name: Create temporary key directory
      delegate_to: localhost
      ansible.builtin.tempfile:
        state: directory
        prefix: ansible_ssh_keypair__
      register: restic_client_ssh_keypair_dir
```

This fails with:

```
fatal: [slinger.internal -> localhost]: FAILED! => {                   
    "changed": false,                                                                                    
    "module_stderr": "/bin/sh: 1: /home/slinger/.ansible_venv/bin/python: not found\n",
    "module_stdout": "",                                                                                 
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127                                                                                                                                                                                                      
}
```

Debug info shows:

> 👀 FYI the first line hints at the bug - "parallels" is the name of this controller machine _and_ I've delegated this create dir to localhost ...

```
<slinger.internal> EXEC /bin/sh -c '/home/slinger/.ansible_venv/bin/python /home/parallels/.ansible/tmp/ansible-tmp-1732883918.9196537-31272-272368415887267/AnsiballZ_tempfile.py && sleep 0'                     
 31139 1732883919.05504: opening command with Popen()                                                                                                                                                              
 31139 1732883919.05809: done running command with Popen()                                                                                                                                                         
 31139 1732883919.05825: getting output with communicate()
 31139 1732883919.06049: done communicating                                                              
 31139 1732883919.06061: done with local.exec_command()                                           
 31139 1732883919.06065: _low_level_execute_command() done: rc=127, stdout=, stderr=/bin/sh: 1: /home/slinger/.ansible_venv/bin/python: not found
 31139 1732883919.06118: done with _execute_module (ansible.builtin.tempfile, {'state': 'directory', 'prefix': 'ansible_ssh_keypair__', '_ansible_check_mode': False, '_ansible_no_log': False, '_ansible_debug': T
rue, '_ansible_diff': False, '_ansible_verbosity': 4, '_ansible_version': '2.18.0', '_ansible_module_name': 'ansible.builtin.tempfile', '_ansible_syslog_facility': 'LOG_USER', '_ansible_selinux_special_fs': ['fu
se', 'nfs', 'vboxsf', 'ramfs', '9p', 'vfat'], '_ansible_string_conversion_action': 'warn', '_ansible_socket': None, '_ansible_shell_executable': '/bin/sh', '_ansible_keep_remote_files': False, '_ansible_tmpdir':
 '/home/parallels/.ansible/tmp/ansible-tmp-1732883918.9196537-31272-272368415887267/', '_ansible_remote_tmp': '~/.ansible/tmp', '_ansible_ignore_unknown_opts': False, '_ansible_target_log_info': None})
```

So it looks like when I delegate things to the controller, _THAT_ is also getting affected by the ansible Python interpreter variable - but things on the host work OK as far as I can tell.

## `uv pip` install failing

I've been able to reproduce the bug you showed above. Here's a playbook:

```yaml
---

- name: Set up slinger
  hosts: slinger
  remote_user: slinger

  vars:
    ansible_venv_dir: "/home/slinger/.ansible_venv"
    ansible_python_interpreter: "{{ ansible_venv_dir }}/bin/python"

  tasks:
    - name: Install paramiko
      moreati.uv.pip:
        name: paramiko
        virtualenv: "{{ ansible_venv_dir }}"
```

Here's the same error (I think):

```
TASK [Install paramiko] *******************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'packaging'
fatal: [slinger.internal]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (packaging) on slinger.internal's Python /home/slinger/.ansible_venv/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

I've got it to run by adding more bootstrap - using `uv pip` to install `packaging` gets it to pass:

```console
slinger@slinger:~ $ . .ansible_venv/bin/activate 
(.ansible_venv) slinger@slinger:~ $ uv pip install packaging
Using Python 3.13.0 environment at: .ansible_venv
Resolved 1 package in 197ms
Prepared 1 package in 66ms
Installed 1 package in 9ms
 + packaging==24.2
(.ansible_venv) slinger@slinger:~ $ uv pip list
Using Python 3.13.0 environment at: .ansible_venv
Package   Version
--------- -------
packaging 24.2
```

The playbook then passes when called again. After running we can see paramiko installed:

```console
(.ansible_venv) slinger@slinger:~ $ uv pip list
Using Python 3.13.0 environment at: .ansible_venv
Package      Version
------------ -------
bcrypt       4.2.1
cffi         1.17.1
cryptography 44.0.0
packaging    24.2
paramiko     3.5.0
pycparser    2.22
pynacl       1.5.0
```

Thanks for reading my brain dump 🧠 - not sure what's next. I'll have a think and post some ideas here later 👍🏻

**Comment by moreati** [comment]
Created https://github.com/moreati/ansible-uv/issues/2

**Comment by moreati** [comment]
> So it looks like when I delegate things to the controller, _THAT_ is also getting affected by the ansible Python interpreter variable - but things on the host work OK as far as I can tell.

I think that behaviour of `delegate_to` is by design. Play scoped variable overrides apply to all hosts in that play, including delegated hosts. This might do what you desire, but I've not tested it:
```yaml
# host_vars/slinger.yml
my_python_interpreter: /home/slinger/.ansible_venv/bin/python
```
```yaml
# host_vars/localhost.yml
my_python_interpreter: "{{ ansible_playbook_python }}"
```
```yaml
- name: Set up slinger
  hosts: slinger
  remote_user: slinger
  vars:
    ansible_python_interpreter: "{{ my_python_interpreter }}"

  tasks:
    - name: Create temporary key directory
      delegate_to: localhost
      ansible.builtin.tempfile:
        state: directory
        prefix: ansible_ssh_keypair__
      register: restic_client_ssh_keypair_dir
```

Refs
- https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_delegation.html#templating-in-delegation-context
- https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#term-ansible_playbook_python
